services:
  db:
    image: postgres:15-alpine
    container_name: jenseiroku-db
    environment:
      POSTGRES_USER: sachin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: life
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jenseiroku-network


  minio:
    image: minio/minio:latest
    container_name: jenseiroku-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - minio_data:/data
    networks:
      - jenseiroku-network

  backend:
    build: ./backend
    container_name: jenseiroku-backend
    ports:
      - "9090:9090"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - jenseiroku-network
  
  frontend:
    build: ./frontend
    container_name: jenseiroku-frontend
    ports:
      - "4200:4200" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    networks:
      - jenseiroku-network

networks:
  jenseiroku-network:
    driver: bridge

volumes:
  postgres_data: 
  minio_data: